'use client'
import { FormEvent, useRef, useState } from 'react'
import { LogOut, Mic, Send, Volume2, VolumeX, Sparkles } from 'lucide-react'
import { authClient } from '@/lib/auth-client'

type Props = { user: { name: string; email: string } }
export function AssistantWorkspace({ user }: Props) {
  const [messages,setMessages]=useState<{role:'user'|'assistant';content:string}[]>([]); const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const [speaking,setSpeaking]=useState(false); const [listening,setListening]=useState(false); const recognition = useRef<any>(null)
  async function sendMessage(event?: FormEvent) { event?.preventDefault(); const text=input.trim(); if(!text||busy)return; setInput(''); setMessages(m=>[...m,{role:'user',content:text},{role:'assistant',content:''}]); setBusy(true); const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})}); if(!response.ok){setMessages(m=>[...m.slice(0,-1),{role:'assistant',content:'The secure AI channel is unavailable right now. Check your deployment configuration.'}]);setBusy(false);return} const reader=response.body?.getReader(); const decoder=new TextDecoder(); let answer=''; if(reader){while(true){const {done,value}=await reader.read(); if(done)break; answer+=decoder.decode(value); setMessages(m=>[...m.slice(0,-1),{role:'assistant',content:answer}])}} setBusy(false) }
  function toggleListen(){if(listening){recognition.current?.stop();setListening(false);return} const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition; if(!Speech)return; const r=new Speech(); r.lang='en-US'; r.onresult=(e:any)=>setInput(e.results[0][0].transcript); r.onend=()=>setListening(false); recognition.current=r; r.start(); setListening(true)}
  function speak(){const last=[...messages].reverse().find(m=>m.role==='assistant')?.content;if(!last||!('speechSynthesis' in window))return; window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(last);utterance.onstart=()=>setSpeaking(true);utterance.onend=()=>setSpeaking(false);window.speechSynthesis.speak(utterance)}
  return <main className="assistant-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles /></div><div><strong>ANJU AI</strong><span>PRIVATE COMPANION</span></div></div><div className="status"><i /> ONLINE<br /><span>Secure channel active</span></div><div className="memory-card"><span>MEMORY CORE</span><strong>Personal workspace</strong><p>Your conversations are private to this account.</p></div><div className="sidebar-bottom"><div className="user-chip"><div>{user.name.slice(0,1).toUpperCase()}</div><span>{user.name}</span></div><button className="icon-button" aria-label="Sign out" onClick={()=>authClient.signOut().then(()=>location.href='/sign-in')}><LogOut /></button></div></aside><section className="chat-panel"><header className="chat-header"><div><span className="eyebrow">COMMAND CONSOLE / 01</span><h1>Good evening, {user.name.split(' ')[0]}</h1></div><div className="header-actions"><button className="icon-button" aria-label="Read latest response aloud" onClick={speak}>{speaking?<VolumeX/>:<Volume2/>}</button></div></header><div className="transcript">{messages.length===0?<div className="empty-state"><div className="orb"><Sparkles /></div><h2>How can I help?</h2><p>Ask me to think, plan, explain, write, or help you move faster.</p><div className="suggestions"><button onClick={()=>setInput('Help me plan my day')}>Plan my day</button><button onClick={()=>setInput('What should I focus on next?')}>Focus mode</button><button onClick={()=>setInput('Explain something clearly')}>Explain something</button></div></div>:messages.map((message,i)=><article key={i} className={`message ${message.role}`}><div className="message-label">{message.role==='user'?'YOU':'ANJU'}</div><div>{message.content || <span className="typing">Thinking…</span>}</div></article>)}</div><form className="composer" onSubmit={sendMessage}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();sendMessage()}}} placeholder="Speak or type a command…" rows={1} /><button type="button" className={`icon-button ${listening?'active':''}`} aria-label="Use voice input" onClick={toggleListen}><Mic /></button><button type="submit" className="send-button" aria-label="Send message" disabled={busy||!input.trim()}><Send /></button></form><div className="hint">Enter to send · Shift + Enter for a new line · Your memory stays private</div></section></main>
}
